/*
 * Copyright (C) 2026 Philip Langdale <philipl@overt.org>
 * Based on vf_nvoffruc / vf_framerate - Copyright (C) 2012 Mark Himsley
 *
 * This file is part of FFmpeg.
 *
 * FFmpeg is free software; you can redistribute it and/or
 * modify it under the terms of the GNU Lesser General Public
 * License as published by the Free Software Foundation; either
 * version 2.1 of the License, or (at your option) any later version.
 *
 * FFmpeg is distributed in the hope that it will be useful,
 * but WITHOUT ANY WARRANTY; without even the implied warranty of
 * MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the GNU
 * Lesser General Public License for more details.
 *
 * You should have received a copy of the GNU Lesser General Public
 * License along with FFmpeg; if not, write to the Free Software
 * Foundation, Inc., 51 Franklin Street, Fifth Floor, Boston, MA 02110-1301 USA
 */

/**
 * @file
 * Frame-rate up-conversion filter that drives the CUDA kernels used by NVIDIA
 * "Smooth Motion" (the driver-level frame generator in libnvidia-present.so).
 * The kernels were extracted as per-kernel multi-arch fatbins and the forward
 * pass was reverse-engineered by intercepting the live CUDA Driver-API launches.
 *
 * The network is an FP8 conv/attention U-Net.  Per interpolated frame it runs a
 * fixed 25-launch graph: downscale -> conv/attn backbone -> depth_to_space ->
 * conv_out (flow field) -> warp_coarse.  The kernels are fully resolution-
 * PARAMETRIC: the driver runs the same graph with dimensions, grids, scratch
 * sizes and param-block offsets scaled to the native frame size (it does not tile
 * and does not resample to a fixed internal resolution).  smoothmotion_cuda_gen.h
 * reproduces that scaling (derived and validated byte-exact against captures at
 * 512/640/720/900/1024/1080/1440/2160), so this filter supports arbitrary sizes.
 *
 * I/O binding: the two input frames are bound as bindless TEXTURE objects (read
 * with TEX; descriptor = clamp/linear/normalized-coords, packed UNORM_INT8X4 so
 * samples are [0,1]) and the output as a bindless SURFACE object (warp's SUST.P).
 * The handles live in the param block (downscale/warp in_tex0/in_tex1 and the warp
 * out_surf field).  We pass our objects to sm_fill_params via SMHandles and it writes
 * them into the right fields by name, so this filter never patches the block by byte
 * offset - the generated code owns the offsets, derived from the captured ABI.
 *
 * Validated on an RTX 5090 (driver 595.71.05): passthrough is pixel-exact and
 * interpolation reaches ~45 dB PSNR vs ground truth on real content (on par with
 * minterpolate).  The network emits the t=0.5 midpoint, so it is exact for 2x.
 */

#include "libavutil/avassert.h"
#include "libavutil/cuda_check.h"
#include "libavutil/hwcontext.h"
#include "libavutil/hwcontext_cuda_internal.h"
#include "libavutil/opt.h"
#include "libavutil/pixdesc.h"

#include "avfilter.h"
#include "filters.h"
#include "rtx_cuda.h"
#include "video.h"

#include "cuda/load_helper.h"

/* Generated by rtx-video-re from the proprietary NVIDIA library, and
 * installed rather than carried here -- located, together with the cubins and
 * weights it names, through pkg-config (see configure's nvfdata_* checks). */
#include <smoothmotion_cuda_gen.h>

/* The packed array formats the output surface takes; the rest of what this
 * filter needs (CU_TRSF_NORMALIZED_COORDINATES, cuSurfObjectCreate) comes from
 * rtx_cuda.h, which resolves it once per process rather than per instance.
 * PITCH2D textures only accept the base integer formats (the packed
 * UNORM_INT*X4 are array-only); UNSIGNED_INT8/16 with normalized coords still
 * read as [0,1]. */
#ifndef CU_AD_FORMAT_UNORM_INT8X4
#define CU_AD_FORMAT_UNORM_INT8X4 ((CUarray_format)0xc2)
#endif
#ifndef CU_AD_FORMAT_UNSIGNED_INT8
#define CU_AD_FORMAT_UNSIGNED_INT8 ((CUarray_format)0x01)
#endif
#ifndef CU_AD_FORMAT_UNSIGNED_INT16
#define CU_AD_FORMAT_UNSIGNED_INT16 ((CUarray_format)0x02)
#endif

#define SM_CH 4

/* One module id past the per-kernel fatbins, for the conversion PTX this filter
 * carries itself: parking it in the shared module table means ff_rtx_free_graph()
 * unloads it with the rest. */
#define SM_CVT_MID SM_NLAUNCH

typedef struct SmoothMotionContext {
    const AVClass *class;

    /* The shared core owns the device reference, the module table, the arena the
     * scratch buffers are cut from and every image below, and releases the lot in
     * ff_rtx_free_graph().  What stays here is what this filter does differently:
     * a launch list refilled per frame, and its own format conversion. */
    FFRtxCuda   r;

    int W, H;                           ///< frame size the graph is built for

    /* generated graph over the arena's four buffers, sb[] order {W,sA,sB,sC} */
    SMGenLaunch gen[SM_NLAUNCH];
    unsigned long long sb[4];

    /* Inputs are bound as bindless textures DIRECTLY over pitched device memory
     * (CU_RESOURCE_TYPE_PITCH2D), like vf_bwdif_cuda - no input CUDA arrays/copies.
     * The warp textures (t_in*) carry the renderable data (RGBA, or packed Y,U,V);
     * the flow textures (t_fl*) carry what the downscale/optical-flow backbone reads
     * (== warp textures for RGB, or luma-grey Y,Y,Y for YUV).  The OUTPUT must stay
     * a CUDA array: the warp writes it via SUST.P and cuSurfObjectCreate requires
     * an array.  For RGB the input textures are (re)bound per-frame over the source
     * frames -- the only handles this filter owns rather than the core; for YUV
     * they are the pack buffers' own persistent textures. */
    FFRtxImage  *out_img;               ///< network output: array + surface
    FFRtxImage  *warp0, *warp1;         ///< packed input buffers + their textures
    FFRtxImage  *flow0, *flow1;         ///< luma-grey flow buffers + textures (YUV)
    FFRtxImage  *unpack_buf;            ///< output staging for the unpack kernel
    CUtexObject  t_in0, t_in1;
    CUtexObject  t_fl0, t_fl1;

    /* native-YUV support: pack/unpack kernels + the buffers they work over */
    int          is_yuv;                ///< input is a YUV format (output = YUV444P[16])
    int          is_packed_rgb;         ///< packed RGB needing unpack/repack (x2rgb10)
    int          direct_out;            ///< output is a plain array->frame copy (no unpack)
    int          elem_bytes;            ///< bytes per INTERNAL packed pixel (net I/O): 4 or 8
    int          frame_bytes;           ///< bytes per pixel of the actual in/out frame
    CUfunction   fn_pack;               ///< format-specific pack-to-warp+flow
    CUfunction   fn_unpack;             ///< packed -> planar YUV444P[16]

    /* options */
    char *data_dir;
    int   interp_start;
    int   interp_end;
    int   packed;                       ///< emit the network's packed output directly

    /* cadence state (from vf_framerate / vf_nvoffruc) */
    AVRational dest_frame_rate;
    AVRational srce_time_base;
    AVRational dest_time_base;
    int        blend_factor_max;
    enum AVPixelFormat format;

    AVFrame *work;
    AVFrame *f0;
    AVFrame *f1;
    int64_t  pts0, pts1, delta;
    int      flush;
    int64_t  start_pts;
    int64_t  n;
} SmoothMotionContext;

#define CHECK_CU(x) FF_CUDA_CHECK_DL(ctx, s->r.hwctx->internal->cuda_dl, x)
#define OFFSET(x) offsetof(SmoothMotionContext, x)
#define V AV_OPT_FLAG_VIDEO_PARAM
#define F AV_OPT_FLAG_FILTERING_PARAM

/* `data` defaults to SM_DEFAULT_DATA_DIR, which the generated header states --
 * the same <FEAT>_DEFAULT_DATA_DIR the other filters' headers here carry.  It
 * names wherever the extraction tool wrote the files it fitted this table
 * alongside, so the table and the kernels can never silently mismatch.  This
 * file used to rebuild that path itself, from a hardcoded workspace root plus
 * the driver version, which could only be right on one machine.  There is
 * deliberately no fallback: a header lacking the define predates it, and
 * building against it is the very mismatch the define prevents, so it fails
 * here rather than at load time.
 *
 * The layout under it is this feature's own -- the per-kernel fatbins live in a
 * fatbins/ subdirectory rather than loose beside weights.bin as the other
 * features' cubins do -- but that is the data dir's business, not the caller's,
 * so it is derived here and there is one `data` option like everywhere else. */
#define SM_FATBIN_SUBDIR "fatbins"
#define SM_WEIGHTS_FILE  "weights.bin"

static const AVOption smoothmotion_cuda_options[] = {
    /* The network only synthesises the t=0.5 midpoint, so the output rate is
     * always exactly 2x the input - there is no target-rate option. */
    { "interp_start", "point to start interpolation",             OFFSET(interp_start),         AV_OPT_TYPE_INT,    {.i64=15},    0, 255, V|F },
    { "interp_end",   "point to end interpolation",               OFFSET(interp_end),           AV_OPT_TYPE_INT,    {.i64=240},   0, 255, V|F },
    { "data",         "directory with the extracted Smooth Motion kernel fatbins + " SM_WEIGHTS_FILE,
                                                                  OFFSET(data_dir),             AV_OPT_TYPE_STRING, {.str=SM_DEFAULT_DATA_DIR}, 0, 0, V|F },
    /* Emit the network's native packed buffer instead of de-interleaving it:
     * RGB/x2rgb10 -> rgba64 (a plain copy, no repack), YUV -> packed 4:4:4
     * (VUYX 8-bit / XV48LE 16-bit).  Lets a packed-format consumer skip a
     * redundant unpack+repack round-trip. */
    { "packed",       "emit the network's packed output directly", OFFSET(packed),              AV_OPT_TYPE_BOOL,   {.i64=0},     0, 1,   V|F },
    { NULL }
};

AVFILTER_DEFINE_CLASS(smoothmotion_cuda);

FF_RTX_ASSERT_PRIV_LAYOUT(SmoothMotionContext);

/* ------------------------------------------------------------------------- *
 * Kernel loading (table-driven, modules deduplicated by name)
 * ------------------------------------------------------------------------- */
/* Every fatbin the driver ships carries every architecture it supports, so a
 * module that will not load means this data dir was built without them. */
#define SM_LOAD_HINT \
    "Re-run `rtxv extract smoothmotion <libnvidia-present.so>` and " \
    "`rtxv install`: the kernels are carved out of the driver as whole " \
    "fatbins, already carrying every arch it ships."

static int load_kernels(AVFilterContext *ctx)
{
    SmoothMotionContext *s = ctx->priv;
    FFRtxModule mods[SM_NLAUNCH];
    FFRtxFunc   funcs[SM_NLAUNCH];
    const char *modname[SM_NLAUNCH];
    char        files[SM_NLAUNCH][80];
    char        dir[1024];
    int         nmod = 0;

    /* One multi-arch fatbin per kernel, deduplicated by name -- several launches
     * run the same kernel.  The driver picks the cubin matching the device's arch
     * (cuModuleLoadData accepts a fatbin image). */
    for (int i = 0; i < SM_NLAUNCH; i++) {
        const char *name = sm_kernel_names[i];
        int m;

        for (m = 0; m < nmod; m++)
            if (!strcmp(modname[m], name))
                break;
        if (m == nmod) {
            snprintf(files[m], sizeof(files[m]), "%s.fatbin", name);
            modname[m]   = name;
            mods[m].mid  = m;
            mods[m].file = files[m];
            nmod++;
        }
        funcs[i].fid  = i;
        funcs[i].mid  = m;
        funcs[i].name = name;
    }
    snprintf(dir, sizeof(dir), "%s/%s", s->data_dir, SM_FATBIN_SUBDIR);

    /* One module id past the fatbins is reserved for the conversion PTX. */
    return ff_rtx_load_modules(ctx, &s->r, dir, mods, nmod, SM_CVT_MID,
                               funcs, SM_NLAUNCH, SM_NLAUNCH - 1, SM_LOAD_HINT);
}

static int format_is_planar444_16(enum AVPixelFormat fmt);
static int format_is_packed_yuv(enum AVPixelFormat fmt);

/* The element format the input textures read: PITCH2D takes only the base
 * integer types, and UNSIGNED_INT8/16 with normalized coords still read as
 * [0,1], matching the array path byte for byte. */
static CUarray_format sm_tex_format(const SmoothMotionContext *s)
{
    return s->elem_bytes == 8 ? CU_AD_FORMAT_UNSIGNED_INT16
                              : CU_AD_FORMAT_UNSIGNED_INT8;
}

/* Bind a texture over a source frame's own memory (the straight-through RGB
 * path, which the network reads without a pack pass).  Rebound per frame, so
 * unlike every other handle here it is this filter's to destroy. */
static int make_input_tex(AVFilterContext *ctx, CUdeviceptr ptr, size_t pitch,
                          CUtexObject *tex)
{
    SmoothMotionContext *s = ctx->priv;

    return ff_rtx_tex_over_pitch(ctx, &s->r, ptr, pitch, s->W, s->H,
                                 sm_tex_format(s), FF_RTX_CLAMP, tex);
}

/* ------------------------------------------------------------------------- *
 * Allocate scratch + weights, generate the graph for WxH, build I/O objects.
 * Must be called with the CUDA context current.
 * ------------------------------------------------------------------------- */
/* The four scratch buffers the generated graph works over, order {W,sA,sB,sC};
 * the weights land in the first. */
static void fill_sizes(AVFilterContext *ctx, long long *sz)
{
    SmoothMotionContext *s = ctx->priv;
    unsigned long long v[4];

    sm_scratch_sizes(s->W, s->H, v);
    for (int a = 0; a < 4; a++)
        sz[a] = (long long)v[a];
}

/* The pack/unpack kernel pair for the input format, out of the conversion PTX. */
static int setup_convert_kernels(AVFilterContext *ctx)
{
    extern const unsigned char ff_vf_smoothmotion_cuda_ptx_data[];
    extern const unsigned int  ff_vf_smoothmotion_cuda_ptx_len;
    SmoothMotionContext *s = ctx->priv;
    CudaFunctions *cu = s->r.hwctx->internal->cuda_dl;
    const char *packfn, *unpackfn;
    int ret;

    /* packed RGB (x2rgb10) unpacks to RGBA16 and repacks (no chroma, and no
     * separate luma-grey flow buffer since the net derives luma internally);
     * YUV packs to (Y,U,V) + luma-grey flow and de-interleaves to planar. */
    if (s->is_packed_rgb) {
        packfn   = s->format == AV_PIX_FMT_X2BGR10LE ? "Pack_x2bgr10" : "Pack_x2rgb10";
        unpackfn = s->format == AV_PIX_FMT_X2BGR10LE ? "Unpack_x2bgr10" : "Unpack_x2rgb10";
    } else {
        packfn   = s->format == AV_PIX_FMT_NV12    ? "Pack_nv12" :
                   s->format == AV_PIX_FMT_NV16    ? "Pack_nv16" :
                   s->format == AV_PIX_FMT_YUV420P ? "Pack_yuv420p" :
                   s->format == AV_PIX_FMT_YUV444P ? "Pack_yuv444p" :
                   format_is_planar444_16(s->format) ? "Pack_yuv444p16" :
                   /* packed 4:4:4 YUV */
                   s->format == AV_PIX_FMT_VUYX ||
                   s->format == AV_PIX_FMT_VUYA    ? "Pack_vuyx" :
                   s->format == AV_PIX_FMT_UYVA    ? "Pack_uyva" :
                   s->format == AV_PIX_FMT_AYUV    ? "Pack_ayuv" :
                   s->format == AV_PIX_FMT_XV48LE  ? "Pack_xv48" :
                   s->format == AV_PIX_FMT_AYUV64LE ? "Pack_ayuv64" :
                   s->format == AV_PIX_FMT_XV30LE  ? "Pack_xv30" :
                   s->format == AV_PIX_FMT_P210 ||
                   s->format == AV_PIX_FMT_P212 ||
                   s->format == AV_PIX_FMT_P216    ? "Pack_p216" :
                                                     "Pack_p016";   /* P010/P016 */
        /* The warp buffer is already interleaved in VUYX / XV48LE order, so
         * `packed` output is a direct copy (no unpack kernel); only the planar
         * path needs to de-interleave. */
        unpackfn = s->elem_bytes == 8 ? "Unpack_yuv444p16" : "Unpack_yuv444p";
    }

    /* Loaded into the module table's reserved slot so it is unloaded with the
     * fatbins rather than needing a teardown of its own. */
    ret = ff_cuda_load_module(ctx, s->r.hwctx, &s->r.mod[SM_CVT_MID],
                              ff_vf_smoothmotion_cuda_ptx_data,
                              ff_vf_smoothmotion_cuda_ptx_len);
    if (ret < 0)
        return ret;
    if ((ret = CHECK_CU(cu->cuModuleGetFunction(&s->fn_pack, s->r.mod[SM_CVT_MID],
                                                packfn))) < 0)
        return ret;
    return CHECK_CU(cu->cuModuleGetFunction(&s->fn_unpack, s->r.mod[SM_CVT_MID],
                                            unpackfn));
}

static int setup_graph(AVFilterContext *ctx)
{
    SmoothMotionContext *s = ctx->priv;
    long long sz[4];
    FFRtxUpload up;
    int ret;

    if ((ret = load_kernels(ctx)) < 0)
        return ret;

    /* One contiguous arena for the four scratch buffers, zeroed so any scratch a
     * kernel reads before writing is deterministically 0.  Contiguity is the
     * shared core's guarantee against a tile/halo read past a buffer's end
     * landing in an unmapped hole once the heap fragments. */
    if ((ret = ff_rtx_alloc_arena(ctx, &s->r, 4, fill_sizes, FF_RTX_ARENA_ZERO)) < 0)
        return ret;
    for (int a = 0; a < 4; a++)
        s->sb[a] = (unsigned long long)s->r.alloc[a];
    /* the param graph (s->gen) is filled per-frame in interpolate_frame, once the
     * tex/surf handles for the current frames exist (see sm_fill_params + SMHandles) */

    /* weights -> sb[0] (the W buffer), which is sized for exactly them */
    fill_sizes(ctx, sz);
    up.file_off = 0;
    up.size     = sz[0];
    up.dst      = (uint64_t)s->r.alloc[0];
    if ((ret = ff_rtx_upload_weights(ctx, &s->r, s->data_dir, SM_WEIGHTS_FILE,
                                     &up, 1)) < 0)
        return ret;

    /* OUTPUT array + surface: the warp writes via SUST.P, and cuSurfObjectCreate
     * requires a CUDA array (no pitch2d/linear surfaces).  Packed UNORM_INT8X4/16X4
     * makes the (unused) texture path return [0,1]; SURFACE_LDST enables SUST.P. */
    s->out_img = ff_rtx_image_array(ctx, &s->r, s->W, s->H,
                                    s->elem_bytes == 8 ? CU_AD_FORMAT_UNORM_INT16X4
                                                       : CU_AD_FORMAT_UNORM_INT8X4,
                                    FF_RTX_SURF | FF_RTX_LDST);
    if (!s->out_img)
        return AVERROR_EXTERNAL;

    /* YUV and packed RGB: the pack/unpack kernels plus the persistent buffers
     * both frames are packed into, each carrying its own input texture.  (The
     * straight-through RGB path binds its textures per frame over the source
     * frames instead, in interpolate_frame.) */
    if (s->is_yuv || s->is_packed_rgb) {
        const CUarray_format tf = sm_tex_format(s);
        const unsigned tex = FF_RTX_TEX | FF_RTX_CLAMP;

        if ((ret = setup_convert_kernels(ctx)) < 0)
            return ret;

        s->warp0 = ff_rtx_image_pitch(ctx, &s->r, s->W, s->H, tf, s->elem_bytes, tex);
        s->warp1 = ff_rtx_image_pitch(ctx, &s->r, s->W, s->H, tf, s->elem_bytes, tex);
        s->unpack_buf = ff_rtx_image_pitch(ctx, &s->r, s->W, s->H, tf, s->elem_bytes, 0);
        if (!s->warp0 || !s->warp1 || !s->unpack_buf)
            return AVERROR_EXTERNAL;
        s->t_in0 = s->warp0->tex;
        s->t_in1 = s->warp1->tex;

        if (s->is_packed_rgb) {
            /* RGB: the downscale/flow backbone reads the same RGBA as the warp */
            s->t_fl0 = s->t_in0;
            s->t_fl1 = s->t_in1;
        } else {
            s->flow0 = ff_rtx_image_pitch(ctx, &s->r, s->W, s->H, tf, s->elem_bytes, tex);
            s->flow1 = ff_rtx_image_pitch(ctx, &s->r, s->W, s->H, tf, s->elem_bytes, tex);
            if (!s->flow0 || !s->flow1)
                return AVERROR_EXTERNAL;
            s->t_fl0 = s->flow0->tex;
            s->t_fl1 = s->flow1->tex;
        }
    }

    av_log(ctx, AV_LOG_INFO, "Smooth Motion graph generated for %dx%d "
           "(arena %.1f MiB)\n", s->W, s->H, (double)s->r.arena_size / (1 << 20));
    return 0;
}
/* ------------------------------------------------------------------------- *
 * Interpolation: replay the generated 25-launch graph.
 * ------------------------------------------------------------------------- */
/* array->device (output CUDA array -> linear packed buffer for unpack) */
static int copy_array_to_lin(AVFilterContext *ctx, CUarray src, const FFRtxImage *dst)
{
    SmoothMotionContext *s = ctx->priv;
    CudaFunctions *cu = s->r.hwctx->internal->cuda_dl;
    CUDA_MEMCPY2D c = { 0 };
    c.srcMemoryType = CU_MEMORYTYPE_ARRAY;  c.srcArray = src;
    c.dstMemoryType = CU_MEMORYTYPE_DEVICE; c.dstDevice = dst->ptr; c.dstPitch = dst->pitch;
    c.WidthInBytes = s->W * s->elem_bytes; c.Height = s->H;
    return CHECK_CU(cu->cuMemcpy2DAsync(&c, s->r.stream));
}

/* pack a YUV source frame into the packed warp buffer (Y,U,V,255) and, if flow
 * != 0, the luma-grey flow buffer (Y,Y,Y,255), upsampling 4:2:0 chroma. */
static int launch_pack(AVFilterContext *ctx, AVFrame *src,
                       const FFRtxImage *warp_img, const FFRtxImage *flow_img)
{
    SmoothMotionContext *s = ctx->priv;
    CudaFunctions *cu = s->r.hwctx->internal->cuda_dl;
    CUdeviceptr warp = warp_img->ptr, flow = flow_img ? flow_img->ptr : 0;
    int W = s->W, H = s->H, pw = warp_img->pitch;
    int pf = flow_img ? (int)flow_img->pitch : 0;
    CUdeviceptr p0 = (CUdeviceptr)src->data[0];
    CUdeviceptr p1 = (CUdeviceptr)src->data[1];
    CUdeviceptr p2 = (CUdeviceptr)src->data[2];
    int l0 = src->linesize[0], l1 = src->linesize[1], l2 = src->linesize[2];
    unsigned bx = (W + 15) / 16, by = (H + 15) / 16;

    /* packed RGB (x2rgb10): one 32-bit-word plane -> RGBA16 warp buffer.  The
     * flow texture aliases the warp buffer (set up in setup_graph), so no flow
     * store; the flow argument is ignored. */
    if (s->is_packed_rgb) {
        void *args[] = { &p0,&l0, &warp,&pw, &W,&H };
        return CHECK_CU(cu->cuLaunchKernel(s->fn_pack, bx, by, 1, 16, 16, 1,
                                           0, s->r.stream, args, NULL));
    }

    /* packed 4:4:4 YUV: one interleaved plane -> warp + luma-grey flow */
    if (format_is_packed_yuv(s->format)) {
        void *args[] = { &p0,&l0, &warp,&pw, &flow,&pf, &W,&H };
        return CHECK_CU(cu->cuLaunchKernel(s->fn_pack, bx, by, 1, 16, 16, 1,
                                           0, s->r.stream, args, NULL));
    }

    /* semi-planar (NV12/NV16/P0xx/P2xx): 2 planes;
     * planar (YUV420P/YUV444P): 3 planes */
    int semiplanar = s->format == AV_PIX_FMT_NV12 ||
                     s->format == AV_PIX_FMT_NV16 ||
                     s->format == AV_PIX_FMT_P010 ||
                     s->format == AV_PIX_FMT_P016 ||
                     s->format == AV_PIX_FMT_P210 ||
                     s->format == AV_PIX_FMT_P212 ||
                     s->format == AV_PIX_FMT_P216;
    void *args_semi[]   = { &p0,&l0, &p1,&l1, &warp,&pw, &flow,&pf, &W,&H };
    void *args_planar[] = { &p0,&l0, &p1,&l1, &p2,&l2, &warp,&pw, &flow,&pf, &W,&H };
    void **args = semiplanar ? args_semi : args_planar;

    return CHECK_CU(cu->cuLaunchKernel(s->fn_pack, bx, by, 1, 16, 16, 1,
                                       0, s->r.stream, args, NULL));
}

/* de-interleave the linear packed buffer into a planar YUV444P frame */
static int launch_unpack(AVFilterContext *ctx, const FFRtxImage *src_img, AVFrame *dst)
{
    SmoothMotionContext *s = ctx->priv;
    CudaFunctions *cu = s->r.hwctx->internal->cuda_dl;
    CUdeviceptr src = src_img->ptr;
    int W = s->W, H = s->H, ps = src_img->pitch;
    CUdeviceptr y = (CUdeviceptr)dst->data[0];
    CUdeviceptr u = (CUdeviceptr)dst->data[1];
    CUdeviceptr v = (CUdeviceptr)dst->data[2];
    int ly = dst->linesize[0], lu = dst->linesize[1], lv = dst->linesize[2];
    unsigned bx = (W + 15) / 16, by = (H + 15) / 16;

    /* packed RGB (x2rgb10): RGBA16 -> a single 32-bit-word plane */
    if (s->is_packed_rgb) {
        void *rgb_args[] = { &src,&ps, &y,&ly, &W,&H };
        return CHECK_CU(cu->cuLaunchKernel(s->fn_unpack, bx, by, 1, 16, 16, 1,
                                           0, s->r.stream, rgb_args, NULL));
    }

    void *args[] = { &src,&ps, &y,&ly, &u,&lu, &v,&lv, &W,&H };
    return CHECK_CU(cu->cuLaunchKernel(s->fn_unpack, bx, by, 1, 16, 16, 1,
                                       0, s->r.stream, args, NULL));
}

/* Emit a source frame through the output hwframe pool (device->device copy) so
 * every frame leaving the filter shares one hwframe context. */
static int passthrough_frame(AVFilterContext *ctx, AVFrame *src)
{
    SmoothMotionContext *s = ctx->priv;
    AVFilterLink *outlink = ctx->outputs[0];
    CudaFunctions *cu = s->r.hwctx->internal->cuda_dl;
    CUDA_MEMCPY2D c = { 0 };
    int ret;

    s->work = ff_get_video_buffer(outlink, outlink->w, outlink->h);
    if (!s->work)
        return AVERROR(ENOMEM);
    av_frame_copy_props(s->work, src);

    if (s->is_yuv && !s->packed) {
        /* convert the source (4:2:0/4:4:4) to the YUV444P output: pack (chroma
         * upsample) then de-interleave; no network, no flow buffer.  lin_warp0 is
         * free scratch here (no interpolation in flight). */
        if ((ret = launch_pack(ctx, src, s->warp0, NULL)) < 0)
            return ret;
        if ((ret = launch_unpack(ctx, s->warp0, s->work)) < 0)
            return ret;
        /* No sync: the unpack into s->work is stream-ordered w.r.t. any
         * same-stream downstream consumer, and nothing here depends on the
         * host observing completion (matches every other CUDA filter). */
        return 0;
    }

    if (s->packed && (s->is_yuv || s->is_packed_rgb)) {
        /* packed output: the pack kernel already writes the warp buffer in the
         * output frame's byte order (VUYX / XV48LE for YUV, RGBA16 for x2rgb10),
         * so run it into scratch and copy that out - no network, no repack.
         * lin_warp0 is free here (no interpolation). */
        if ((ret = launch_pack(ctx, src, s->warp0, NULL)) < 0)
            return ret;
        c.srcMemoryType = CU_MEMORYTYPE_DEVICE;
        c.srcDevice = s->warp0->ptr;
        c.srcPitch = s->warp0->pitch;
        c.dstMemoryType = CU_MEMORYTYPE_DEVICE;
        c.dstDevice = (CUdeviceptr)s->work->data[0];
        c.dstPitch = s->work->linesize[0];
        c.WidthInBytes = s->W * s->elem_bytes;   /* interleaved 4-channel pixel */
        c.Height = s->H;
        return CHECK_CU(cu->cuMemcpy2DAsync(&c, s->r.stream));
    }

    c.srcMemoryType = CU_MEMORYTYPE_DEVICE;
    c.srcDevice = (CUdeviceptr)src->data[0];
    c.srcPitch = src->linesize[0];
    c.dstMemoryType = CU_MEMORYTYPE_DEVICE;
    c.dstDevice = (CUdeviceptr)s->work->data[0];
    c.dstPitch = s->work->linesize[0];
    /* straight-through copy (RGB, rgba64, or x2rgb10 -> x2rgb10): frame_bytes is
     * the true per-pixel size (4 for x2rgb10; elem_bytes is its internal 8). */
    c.WidthInBytes = s->W * s->frame_bytes;
    c.Height = s->H;
    /* device->device async copy on the stream; no host-side sync needed - the
     * result is ordered for any same-stream consumer downstream. */
    return CHECK_CU(cu->cuMemcpy2DAsync(&c, s->r.stream));
}

static int interpolate_frame(AVFilterContext *ctx, int64_t work_pts)
{
    SmoothMotionContext *s = ctx->priv;
    AVFilterLink *outlink = ctx->outputs[0];
    CudaFunctions *cu = s->r.hwctx->internal->cuda_dl;
    int ret;

    s->work = ff_get_video_buffer(outlink, outlink->w, outlink->h);
    if (!s->work)
        return AVERROR(ENOMEM);
    av_frame_copy_props(s->work, s->f0);

    if (s->is_yuv || s->is_packed_rgb) {
        /* pack both frames into their persistent warp (+ luma-grey flow, YUV
         * only) buffers; the input textures are already bound over these
         * (setup_graph).  For packed RGB lin_flow* is unallocated (0) and ignored. */
        if ((ret = launch_pack(ctx, s->f0, s->warp0, s->flow0)) < 0) return ret;
        if ((ret = launch_pack(ctx, s->f1, s->warp1, s->flow1)) < 0) return ret;
    } else {
        /* RGB: bind input textures directly over the source frames (no copy).
         * downscale reads the same RGB textures as the warp (t_fl* == t_in*). */
        if ((ret = make_input_tex(ctx, (CUdeviceptr)s->f0->data[0],
                                  s->f0->linesize[0], &s->t_in0)) < 0) return ret;
        if ((ret = make_input_tex(ctx, (CUdeviceptr)s->f1->data[0],
                                  s->f1->linesize[0], &s->t_in1)) < 0) return ret;
        s->t_fl0 = s->t_in0;
        s->t_fl1 = s->t_in1;
    }

    /* fill the graph with the current frames' tex/surf handles; sm_fill_params writes
     * them into in_tex0/in_tex1/out_surf, so no by-offset patching here.  The flow
     * (downscale) path uses the luma textures for YUV, == the warp textures for RGB. */
    SMHandles h = {
        .flow_tex = { s->t_fl0, s->t_fl1 },
        .warp_tex = { s->t_in0, s->t_in1 },
        .out_surf = s->out_img->surf,
    };
    sm_fill_params(s->W, s->H, s->gen, s->sb, &h);

    for (int i = 0; i < SM_NLAUNCH; i++) {
        SMGenLaunch *L = &s->gen[i];
        void *kp[1] = { L->params };

        ret = CHECK_CU(cu->cuLaunchKernel(s->r.fn[i],
                                          L->grid[0], L->grid[1], L->grid[2],
                                          L->block[0], L->block[1], L->block[2],
                                          L->smem, s->r.stream, kp, NULL));
        if (ret < 0)
            return ret;
    }

    /* copy the warp output array back into the work frame */
    if (!s->direct_out) {
        /* packed array -> linear -> planar YUV444P, packed 4:4:4, or repacked
         * x2rgb10 (whichever fn_unpack selects) */
        if ((ret = copy_array_to_lin(ctx, s->out_img->arr, s->unpack_buf)) < 0)
            return ret;
        if ((ret = launch_unpack(ctx, s->unpack_buf, s->work)) < 0)
            return ret;
    } else {
        CUDA_MEMCPY2D c = { 0 };
        c.srcMemoryType = CU_MEMORYTYPE_ARRAY;
        c.srcArray = s->out_img->arr;
        c.dstMemoryType = CU_MEMORYTYPE_DEVICE;
        c.dstDevice = (CUdeviceptr)s->work->data[0];
        c.dstPitch = s->work->linesize[0];
        c.WidthInBytes = s->W * s->elem_bytes;
        c.Height = s->H;
        if ((ret = CHECK_CU(cu->cuMemcpy2DAsync(&c, s->r.stream))) < 0)
            return ret;
    }

    /* RGB input textures are bound per-frame over the source frames; release them
     * now that the launches have completed (YUV textures are persistent).  This
     * is the only sync the filter needs: cuTexObjectDestroy is a host call with
     * no stream ordering, so the downscale/warp launches that read these textures
     * must be drained first.  The YUV and packed-RGB paths have persistent
     * textures (no per-frame destroy) and are fully stream-ordered downstream,
     * so they return without blocking. */
    if (!s->is_yuv && !s->is_packed_rgb) {
        ret = CHECK_CU(cu->cuStreamSynchronize(s->r.stream));
        if (s->t_in0) CHECK_CU(cu->cuTexObjectDestroy(s->t_in0));
        if (s->t_in1) CHECK_CU(cu->cuTexObjectDestroy(s->t_in1));
        s->t_in0 = s->t_in1 = s->t_fl0 = s->t_fl1 = 0;
    }
    return ret;
}

/* cadence: choose / synthesize the next output frame (from vf_nvoffruc) */
static int process_work_frame(AVFilterContext *ctx)
{
    SmoothMotionContext *s = ctx->priv;
    int64_t work_pts, interpolate, interpolate8;
    int ret;

    if (!s->f1)
        return 0;
    if (!s->f0 && !s->flush)
        return 0;

    work_pts = s->start_pts + av_rescale_q(s->n, av_inv_q(s->dest_frame_rate),
                                           s->dest_time_base);
    if (work_pts >= s->pts1 && !s->flush)
        return 0;

    if (!s->f0) {
        av_assert1(s->flush);
        ret = passthrough_frame(ctx, s->f1);
        if (ret < 0)
            return ret;
    } else {
        if (work_pts >= s->pts1 + s->delta && s->flush)
            return 0;

        interpolate  = av_rescale(work_pts - s->pts0, s->blend_factor_max, s->delta);
        interpolate8 = av_rescale(work_pts - s->pts0, 256, s->delta);

        if (interpolate >= s->blend_factor_max || interpolate8 > s->interp_end) {
            ret = passthrough_frame(ctx, s->f1);
        } else if (interpolate <= 0 || interpolate8 < s->interp_start) {
            ret = passthrough_frame(ctx, s->f0);
        } else {
            ret = interpolate_frame(ctx, work_pts);
        }
        if (ret < 0)
            return ret;
    }

    if (!s->work)
        return AVERROR(ENOMEM);

    s->work->pts = work_pts;
    s->n++;
    return 1;
}

static av_cold int init(AVFilterContext *ctx)
{
    SmoothMotionContext *s = ctx->priv;
    s->start_pts = AV_NOPTS_VALUE;
    return 0;
}

/* Drop the graph.  ff_rtx_free_graph() releases everything the core allocated --
 * the modules, the arena, every image and the device reference -- against the
 * context it was built on; what is left here is the handles this filter owns
 * itself, which alias core-owned textures on the YUV path and so must be
 * dropped rather than destroyed. */
static void free_graph(AVFilterContext *ctx)
{
    SmoothMotionContext *s = ctx->priv;

    ff_rtx_free_graph(ctx, &s->r);
    s->out_img = s->warp0 = s->warp1 = NULL;
    s->flow0 = s->flow1 = s->unpack_buf = NULL;
    s->t_in0 = s->t_in1 = s->t_fl0 = s->t_fl1 = 0;
    s->fn_pack = s->fn_unpack = NULL;
}

static av_cold void uninit(AVFilterContext *ctx)
{
    SmoothMotionContext *s = ctx->priv;

    free_graph(ctx);
    av_frame_free(&s->f0);
    av_frame_free(&s->f1);
}



static const enum AVPixelFormat supported_formats[] = {
    /* RGB: fed straight through (the net derives luma internally) */
    AV_PIX_FMT_RGB0,
    AV_PIX_FMT_BGR0,
    AV_PIX_FMT_RGBA,
    AV_PIX_FMT_BGRA,
    /* 16-bit packed RGBA (64bpp): same straight-through path, 8 bytes/pixel;
     * the texture binds as UNSIGNED_INT16 and the output array as UNORM_INT16X4 */
    AV_PIX_FMT_RGBA64,
    /* packed 10-bit RGB (2:10:10:10, 32bpp): not byte-separable, so it is
     * unpacked to RGBA16 on the way in and repacked on the way out (elem_bytes
     * 8 internally, frame_bytes 4); emitted unchanged (x2rgb10 or x2bgr10) */
    AV_PIX_FMT_X2RGB10LE,
    AV_PIX_FMT_X2BGR10LE,
    /* 8-bit YUV: luma->flow, packed YUV->warp, emitted as planar YUV444P
     * (NV16 is 4:2:2; chroma upsampled horizontally only) */
    AV_PIX_FMT_NV12,
    AV_PIX_FMT_NV16,
    AV_PIX_FMT_YUV420P,
    AV_PIX_FMT_YUV444P,
    /* 16-bit YUV (P010 10-bit, P016 16-bit 4:2:0; P210 10-bit, P212 12-bit,
     * P216 16-bit 4:2:2; planar 4:4:4 incl. 10/12-bit MSB-aligned which share
     * YUV444P16's uint16 layout): emitted as YUV444P16 */
    AV_PIX_FMT_P010,
    AV_PIX_FMT_P016,
    AV_PIX_FMT_P210,
    AV_PIX_FMT_P212,
    AV_PIX_FMT_P216,
    AV_PIX_FMT_YUV444P16,
    AV_PIX_FMT_YUV444P10MSB,
    AV_PIX_FMT_YUV444P12MSB,
    /* packed 4:4:4 YUV: one interleaved plane, chroma already full-res.  8-bit
     * (VUYX/VUYA, UYVA, AYUV), 16-bit (XV48LE, AYUV64LE) and packed 10-bit
     * (XV30LE, 2:10:10:10 -> RGBA16 internal).  Same is_yuv pack/unpack path;
     * the alpha/X channel is ignored. */
    AV_PIX_FMT_VUYX,
    AV_PIX_FMT_VUYA,
    AV_PIX_FMT_UYVA,
    AV_PIX_FMT_AYUV,
    AV_PIX_FMT_XV48LE,
    AV_PIX_FMT_AYUV64LE,
    AV_PIX_FMT_XV30LE,
    AV_PIX_FMT_NONE
};

static int format_is_supported(enum AVPixelFormat fmt)
{
    for (int i = 0; i < FF_ARRAY_ELEMS(supported_formats); i++)
        if (supported_formats[i] == fmt)
            return 1;
    return 0;
}

/* planar 16-bit 4:4:4: full-res uint16 planes (incl. 10/12-bit MSB-aligned, which
 * share YUV444P16's layout; the UNORM_INT16 normalize absorbs the MSB scaling) */
static int format_is_planar444_16(enum AVPixelFormat fmt)
{
    return fmt == AV_PIX_FMT_YUV444P16 ||
           fmt == AV_PIX_FMT_YUV444P10MSB ||
           fmt == AV_PIX_FMT_YUV444P12MSB;
}

/* packed 4:4:4 YUV in one interleaved plane (chroma already full-res); the
 * 16-bit and 10-bit members are routed through format_is_16bit below */
static int format_is_packed_yuv(enum AVPixelFormat fmt)
{
    return fmt == AV_PIX_FMT_VUYX ||
           fmt == AV_PIX_FMT_VUYA ||
           fmt == AV_PIX_FMT_UYVA ||
           fmt == AV_PIX_FMT_AYUV ||
           fmt == AV_PIX_FMT_XV48LE ||
           fmt == AV_PIX_FMT_AYUV64LE ||
           fmt == AV_PIX_FMT_XV30LE;
}

static int format_is_16bit(enum AVPixelFormat fmt)
{
    return fmt == AV_PIX_FMT_P010 ||
           fmt == AV_PIX_FMT_P016 ||
           fmt == AV_PIX_FMT_P210 ||
           fmt == AV_PIX_FMT_P212 ||
           fmt == AV_PIX_FMT_P216 ||
           fmt == AV_PIX_FMT_XV48LE ||     /* packed 4:4:4, 16-bit */
           fmt == AV_PIX_FMT_AYUV64LE ||
           fmt == AV_PIX_FMT_XV30LE ||     /* packed 4:4:4, 10-bit -> 16-bit */
           format_is_planar444_16(fmt);
}

/* packed RGB that is not byte-separable (bit-packed fields), so it needs an
 * unpack-to-RGBA16 / repack pass rather than a direct texture bind */
static int format_is_packed_rgb(enum AVPixelFormat fmt)
{
    return fmt == AV_PIX_FMT_X2RGB10LE ||
           fmt == AV_PIX_FMT_X2BGR10LE;
}

static int format_is_yuv(enum AVPixelFormat fmt)
{
    return fmt == AV_PIX_FMT_NV12 ||
           fmt == AV_PIX_FMT_NV16 ||
           fmt == AV_PIX_FMT_YUV420P ||
           fmt == AV_PIX_FMT_YUV444P ||
           format_is_packed_yuv(fmt) ||
           format_is_16bit(fmt);
}

static int activate(AVFilterContext *ctx)
{
    int ret, status;
    AVFilterLink *inlink = ctx->inputs[0];
    AVFilterLink *outlink = ctx->outputs[0];
    SmoothMotionContext *s = ctx->priv;
    AVFrame *inpicref;
    int64_t pts;
    CudaFunctions *cu = s->r.hwctx->internal->cuda_dl;
    CUcontext dummy;

    FF_FILTER_FORWARD_STATUS_BACK(outlink, inlink);

    CHECK_CU(cu->cuCtxPushCurrent(s->r.cu_ctx));

retry:
    ret = process_work_frame(ctx);
    if (ret < 0) {
        goto exit;
    } else if (ret == 1) {
        ret = ff_filter_frame(outlink, s->work);
        goto exit;
    }

    ret = ff_inlink_consume_frame(inlink, &inpicref);
    if (ret < 0)
        goto exit;

    if (inpicref) {
        if (inpicref->flags & AV_FRAME_FLAG_INTERLACED)
            av_log(ctx, AV_LOG_WARNING, "Interlaced frame found - output will not be correct.\n");
        if (inpicref->pts == AV_NOPTS_VALUE) {
            av_log(ctx, AV_LOG_WARNING, "Ignoring frame without PTS.\n");
            av_frame_free(&inpicref);
        }
    }

    if (inpicref) {
        pts = av_rescale_q(inpicref->pts, s->srce_time_base, s->dest_time_base);
        if (s->f1 && pts == s->pts1) {
            av_log(ctx, AV_LOG_WARNING, "Ignoring frame with same PTS.\n");
            av_frame_free(&inpicref);
        }
    }

    if (inpicref) {
        av_frame_free(&s->f0);
        s->f0 = s->f1;
        s->pts0 = s->pts1;
        s->f1 = inpicref;
        s->pts1 = pts;
        s->delta = s->pts1 - s->pts0;

        if (s->delta < 0) {
            av_log(ctx, AV_LOG_WARNING, "PTS discontinuity.\n");
            s->start_pts = s->pts1;
            s->n = 0;
            av_frame_free(&s->f0);
        }
        if (s->start_pts == AV_NOPTS_VALUE)
            s->start_pts = s->pts1;
        goto retry;
    }

    if (ff_inlink_acknowledge_status(inlink, &status, &pts)) {
        if (!s->flush) {
            s->flush = 1;
            goto retry;
        }
        ff_outlink_set_status(outlink, status, pts);
        ret = 0;
        goto exit;
    }

    /* FF_FILTER_FORWARD_WANTED expanded: the macro returns 0 directly, which
     * would skip the pop below and leave our context on the thread's stack -- on
     * the most-taken path through activate(), so it would grow once per frame. */
    if (ff_outlink_frame_wanted(outlink)) {
        ff_inlink_request_frame(inlink);
        ret = 0;
        goto exit;
    }
    ret = FFERROR_NOT_READY;

exit:
    CHECK_CU(cu->cuCtxPopCurrent(&dummy));
    return ret;
}

static int config_input(AVFilterLink *inlink)
{
    AVFilterContext *ctx = inlink->dst;
    SmoothMotionContext *s = ctx->priv;
    s->srce_time_base = inlink->time_base;
    s->blend_factor_max = 1 << (8 - 1);
    return 0;
}

static int config_output(AVFilterLink *outlink)
{
    AVFilterContext *ctx = outlink->src;
    AVFilterLink *inlink = outlink->src->inputs[0];
    FilterLink   *il     = ff_filter_link(inlink);
    FilterLink   *ol     = ff_filter_link(outlink);
    AVHWFramesContext *in_frames_ctx;
    SmoothMotionContext *s = ctx->priv;
    enum AVPixelFormat out_format;
    int exact, ret;

    /* This can run again on a link reconfigure or a graph rebuild; drop the
     * previous graph first so the rebuild neither leaks nor inherits stale
     * device pointers, and drop the buffered source frames with it -- they are
     * sized for the old configuration. */
    free_graph(ctx);
    av_frame_free(&s->f0);
    av_frame_free(&s->f1);
    s->start_pts = AV_NOPTS_VALUE;
    s->n = 0;
    s->flush = 0;

    /* The network emits the midpoint frame, so the output rate is always 2x. */
    s->dest_frame_rate = av_mul_q(il->frame_rate, (AVRational){ 2, 1 });

    exact = av_reduce(&s->dest_time_base.num, &s->dest_time_base.den,
                      av_gcd((int64_t)s->srce_time_base.num * s->dest_frame_rate.num,
                             (int64_t)s->srce_time_base.den * s->dest_frame_rate.den),
                      (int64_t)s->srce_time_base.den * s->dest_frame_rate.num, INT_MAX);
    if (!s->dest_time_base.num || !s->dest_time_base.den) {
        exact = av_reduce(&s->dest_time_base.num, &s->dest_time_base.den,
                          s->dest_frame_rate.den, s->dest_frame_rate.num, INT_MAX);
    }
    av_log(ctx, AV_LOG_INFO, "time base:%u/%u -> %u/%u exact:%d\n",
           s->srce_time_base.num, s->srce_time_base.den,
           s->dest_time_base.num, s->dest_time_base.den, exact);

    ol->frame_rate    = s->dest_frame_rate;
    outlink->time_base = s->dest_time_base;

    if (!il->hw_frames_ctx) {
        av_log(ctx, AV_LOG_ERROR, "No hw context provided on input\n");
        return AVERROR(EINVAL);
    }
    in_frames_ctx = (AVHWFramesContext*)il->hw_frames_ctx->data;
    s->format = in_frames_ctx->sw_format;
    if (!format_is_supported(s->format)) {
        av_log(ctx, AV_LOG_ERROR, "Unsupported input format %s\n",
               av_get_pix_fmt_name(s->format));
        return AVERROR(ENOSYS);
    }
    s->is_yuv = format_is_yuv(s->format);
    s->is_packed_rgb = format_is_packed_rgb(s->format);
    /* 8 bytes/pixel for any 16-bit 4-channel INTERNAL path: the 16-bit YUV
     * formats (routed through format_is_16bit), packed 16-bit RGBA (rgba64), and
     * x2rgb10 (unpacked to RGBA16).  rgba64/x2rgb10 are RGB not YUV, so they are
     * kept out of format_is_16bit/format_is_yuv. */
    s->elem_bytes = (format_is_16bit(s->format) ||
                     s->format == AV_PIX_FMT_RGBA64 ||
                     s->is_packed_rgb) ? 2 * SM_CH : SM_CH;
    /* bytes per pixel of the actual frame; differs from elem_bytes only for
     * x2rgb10 (a 32-bit packed word that unpacks to 8-byte RGBA16 internally). */
    s->frame_bytes = s->is_packed_rgb ? 4 : s->elem_bytes;
    /* output is a plain array->frame copy (no de-interleave kernel) for the
     * straight-through RGB formats, and for every `packed` request: the network
     * already writes VUYX / XV48LE (YUV) or RGBA16 (x2rgb10) in the output
     * frame's byte order, so nothing needs reshuffling. */
    s->direct_out = (!s->is_yuv && !s->is_packed_rgb) || s->packed;
    s->W = inlink->w;
    s->H = inlink->h;
    if (s->W < 64 || s->H < 64)
        av_log(ctx, AV_LOG_WARNING, "Very small frame %dx%d; results may be poor.\n",
               s->W, s->H);

    if ((ret = ff_rtx_bind_device(ctx, &s->r, in_frames_ctx)) < 0)
        return ret;

    /* YUV inputs are emitted as planar 4:4:4 (no output-side chroma downsample);
     * the network produces packed 4:4:4 and we de-interleave it.  16-bit inputs
     * (P010/P016) keep full precision via YUV444P16.  With `packed`, the network
     * buffer is emitted directly: packed 4:4:4 (VUYX / XV48LE) for YUV, and the
     * native RGBA16 (rgba64) for x2rgb10/x2bgr10.  The size is unchanged: this
     * filter interpolates in time, not space. */
    if (s->is_yuv)
        out_format = s->packed ?
            (s->elem_bytes == 8 ? AV_PIX_FMT_XV48LE : AV_PIX_FMT_VUYX) :
            (s->elem_bytes == 8 ? AV_PIX_FMT_YUV444P16 : AV_PIX_FMT_YUV444P);
    else if (s->is_packed_rgb && s->packed)
        out_format = AV_PIX_FMT_RGBA64;
    else
        out_format = s->format;

    if ((ret = ff_rtx_config_hwframes(ctx, outlink, &s->r, s->W, s->H,
                                      out_format)) < 0)
        return ret;

    return ff_rtx_setup(ctx, &s->r, "Smooth Motion", setup_graph);
}

static const AVFilterPad smoothmotion_cuda_inputs[] = {
    { .name = "default", .type = AVMEDIA_TYPE_VIDEO, .config_props = config_input },
};

static const AVFilterPad smoothmotion_cuda_outputs[] = {
    { .name = "default", .type = AVMEDIA_TYPE_VIDEO, .config_props = config_output },
};

const FFFilter ff_vf_smoothmotion_cuda = {
    .p.name        = "smoothmotion_cuda",
    .p.description  = NULL_IF_CONFIG_SMALL("Frame-rate up-conversion using NVIDIA Smooth Motion CUDA kernels"),
    .p.priv_class   = &smoothmotion_cuda_class,
    .priv_size     = sizeof(SmoothMotionContext),
    .init          = init,
    .uninit        = uninit,
    .activate      = activate,
    FILTER_INPUTS(smoothmotion_cuda_inputs),
    FILTER_OUTPUTS(smoothmotion_cuda_outputs),
    FILTER_SINGLE_PIXFMT(AV_PIX_FMT_CUDA),
    .flags_internal = FF_FILTER_FLAG_HWFRAME_AWARE,
};
